### ISSUE TITLE
Error on Blender 2.92 in Linux (Ubuntu 20.04) 

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [shycats/VirtuCameraBlender#1]
Hi I'm getting this error on Blender 2.92, linux 64bits - Ubuntu 20.04. 

![Screenshot from 2021-03-10 07-59-12](https://user-images.githubusercontent.com/346914/110633527-db483a80-8176-11eb-9b1c-c5218602fd64.png)

I will appreciate any hint on how to solve it

Thanks

**Comment by shycats** [comment]
Hello,

It seems that you installed the source code directly, which doesn't include all the needed dependencies.
Please, try downloading the zip specific to linux from the [Releases](https://github.com/shycats/VirtuCameraBlender/releases) section and let me know if it works for you.

Thanks!

**Comment by patriciogonzalezvivo** [comment]
I did download the linux .tar.gz from that link. And install the addon directly from the .zip
And recived that error message. 
Do I need to unzip it first?

**Comment by patriciogonzalezvivo** [comment]
Yes, I can confirm. I download `VirtuCameraBlender-cp37-linux64-v1.0.0.zip` and install it and then when enabling I get that error

**Comment by patriciogonzalezvivo** [comment]
Same message on scripting than in the console out 

```
PYTHON INTERACTIVE CONSOLE 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data
```

**Comment by patriciogonzalezvivo** [comment]
I'm using focal version of blender build here:

```
http://ppa.launchpad.net/thomas-schiex/blender/ubuntu
```

**Comment by shycats** [comment]
Ok it seems to be a modified build of Blender, the one available from blender.org comes with Python 3.7.7.
Anyway, if you need to use this specific Blender build, I can provide you a custom add-on build.

**Comment by patriciogonzalezvivo** [comment]
Sorry for the delay. Yes, my blender install use the system's Python.

```
[~/Desktop]$ python3 -V
Python 3.8.5
```

Could be possible to have a version of VirtuCamera blender addon on made for Ubuntu's 20.04 python's??

**Comment by robinuniverse** [comment]
Having a similar issue to this

`
Traceback (most recent call last):
  File "/usr/share/blender/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/robin/.config/blender/2.92/scripts/addons/virtucamera_blender/__init__.py", line 37, in <module>
    from .virtucamera_blender import *
  File "/home/robin/.config/blender/2.92/scripts/addons/virtucamera_blender/virtucamera_blender.py", line 38, in <module>
    from .virtucamera import VCBase, VCServer
  File "/home/robin/.config/blender/2.92/scripts/addons/virtucamera_blender/virtucamera/__init__.py", line 42, in <module>
    from .vc_core import VCServer
ModuleNotFoundError: No module named 'virtucamera_blender.virtucamera.vc_core'
`
I get this error when I try to enable the add-on. I'm using Blender 3.92 on Arch Linux as it is provided in the AUR. it uses Python 3.9.5, which I expect is the issue. as I expect my working version of python to change often, it might be helpful if you gave an explanation as to how to make the needed changes on our own so you don't have a repeat issue of this - cheers!

**Comment by shycats** [comment]
@patriciogonzalezvivo @robinuniverse If you are using the latest version of the add-on (v1.0.2), you can replace this folder:
```
~/.config/blender/<version>/scripts/addons/virtucamera_blender/virtucamera
```
with one of the versions provided here:
[https://github.com/shycats/PyVirtuCamera/releases/tag/v2.1.0](https://github.com/shycats/PyVirtuCamera/releases/tag/v2.1.0)

You must use a release compatible with your Python version. (e.g.: cp38 for CPython 3.8)

**Comment by robinuniverse** [comment]
This did the trick, thank you!
