### ISSUE TITLE
When recording starts, also start the animation playback in the scene

### ISSUE THREAD

**Issue by sgodanas** [shycats/VirtuCameraBlender#12]
At the moment, when recording takes (after hitting the record button), we have to manually hit playback button in Blender/Maya, so that animation in the scene also plays back.

It will be great if the recording action in the app can call the server callback that plays back the animation (It seems to already exist), but is not called yet.

**Comment by sgodanas** [comment]
@shycats I have also sent you an email to discuss this and a few other things from our Studio. Hoping to hear from you soon. 

Thank you,
Satish.

**Comment by satishgoda** [comment]
Closing this as @shycats informed me that the record button with the play icon does exactly what I need.

**Comment by sgodanas** [comment]
Closing this as @shycats informed me that the record button with the play icon does exactly what I need.

**Comment by sgodanas** [comment]
Thank you @shycats for resolving this via e-mail.
