### ISSUE TITLE
VirtuCamera add-on for Python 3.10.* (Blender 3.1.0 and later)

### ISSUE THREAD

**Issue by sgodanas** [shycats/VirtuCameraBlender#13]
Hi.

While Blender 3.0.x uses Python 3.9 version, the upcoming release of Blender, Blender 3.1.0 (slated to be released in March, 2022) is switching to Blender 3.10.2. What is the timeline for releasing the add-on to work with Blender 3.1.0?

Thank you,
Satish.

**Comment by sgodanas** [comment]
@shycats I have also sent an e-mail to you! Looking forward to hearing from you. Thank you :)

**Comment by shycats** [comment]
Hi,

Yes, I'm working on it and the plan is to release it in March. I will let you know when it's ready :)

Best,
Pablo.

**Comment by sgodanas** [comment]
Amazing :) Thank you so much!

**Comment by vogues** [comment]
thanks!

**Comment by sgodanas** [comment]
Hi.

Just pinging to see if the release in March is still happening. We are launching a sequence next week and our DP could really use VirtuCamera in 3.1.

Thank you,
Satish.

**Comment by shycats** [comment]
Hello @sgodanas, @vogues. I've published a pre-release for Blender 3.1. It's only fully tested on MacOS for now and will test it on Windows and Linux as soon as possible. if you use Windows or Linux it may not work properly, but you can give it a try:
[https://github.com/shycats/VirtuCameraBlender/releases/tag/v1.1.1_3.1](https://github.com/shycats/VirtuCameraBlender/releases/tag/v1.1.1_3.1)

Cheers!

**Comment by sgodanas** [comment]
Hi @shycats 

Thank you for providing the pre-release. We will test it our thoroughly and provide any feedback.

Satish.

**Comment by sgodanas** [comment]
I briefly tested the pre-release on Windows 10 and I was able to successfully connect to the server and perform the routine operations.

Will conduct more thorough tests on Monday and update here.

Thank you,
Satish.

**Comment by shycats** [comment]
@sgodanas thank you so much for testing, glad to hear that is working for you :)
I already tested both Linux and Windows builds and they are working fine so I'm releasing them officially and closing this ticket.

Cheers!
