### ISSUE TITLE
Error in Blender 2.92 Mac 

### ISSUE THREAD

**Issue by vanaus** [shycats/VirtuCameraBlender#2]
![Screen Shot 2021-03-10 at 6 04 55 PM](https://user-images.githubusercontent.com/80432708/110715847-a31f1700-81cb-11eb-9713-6bfa8108c489.png)

**Comment by shycats** [comment]
Hello,

I’m sorry that you are getting errors.

It looks related to the MacOS version you are using, please let me know your OS version so I can try to debug it.

Thanks!

**Comment by piotrnikov** [comment]
Hi! Same error here.
<img width="846" alt="Screenshot 2021-03-11 at 10 46 56" src="https://user-images.githubusercontent.com/28474540/110768380-7a446380-8257-11eb-8567-fdde6aa70865.png">
I'm not sure it's related to the MacOs version (I'm on 11.2). Maybe Python?
<img width="929" alt="Screenshot 2021-03-11 at 10 49 19" src="https://user-images.githubusercontent.com/28474540/110768429-84fef880-8257-11eb-87e7-f28e24f05fd6.png">
The addon loads correctly on Blender 2.83.13, so maybe it's Blender related...
Tell me if you need more info, I'm happy to help :)

Piotr

**Comment by shycats** [comment]
> Hi! Same error here.
> <img alt="Screenshot 2021-03-11 at 10 46 56" width="846" src="https://user-images.githubusercontent.com/28474540/110768380-7a446380-8257-11eb-8567-fdde6aa70865.png">
> I'm not sure it's related to the MacOs version (I'm on 11.2). Maybe Python?
> <img alt="Screenshot 2021-03-11 at 10 49 19" width="929" src="https://user-images.githubusercontent.com/28474540/110768429-84fef880-8257-11eb-87e7-f28e24f05fd6.png">
> The addon loads correctly on Blender 2.83.13, so maybe it's Blender related...
> Tell me if you need more info, I'm happy to help :)
> 
> Piotr

Hello Piotr, this looks like a different error, it's failing because Blender 2.93 uses a different version of Python. This version of Blender is not supported yet, as it's a preliminary version. We are working to support it and will release an update soon.

**Comment by piotrnikov** [comment]
@shycats Ah ok, thanks!

**Comment by vanaus** [comment]
> Hello,
> 
> I’m sorry that you are getting errors.
> 
> It looks related to the MacOS version you are using, please let me know your OS version so I can try to debug it.
> 
> Thanks!

I’m currently running High Sierra 10.13.6. At first I was on 10.12.6, was able to install it just fine in blender 2.83, but it just completely crashed the whole program when I tried to apply the addon. So I updated to High Sierra and Blender 2.92 and instead of crashing completely, I just get this error message. Which is somewhat progress lol but not the desired result. Thanks for the help!

**Comment by shycats** [comment]
@vanaus thanks for the info, I will try to make it work on High Sierra but I don't have access to that OS version, would you mind testing a new build when I have it ready, and see if it works?
Thanks!

**Comment by vanaus** [comment]
> @vanaus thanks for the info, I will try to make it work on High Sierra but I don't have access to that OS version, would you mind testing a new build when I have it ready, and see if it works?
> Thanks!

Absolutely! Thanks!

**Comment by shycats** [comment]
@vanaus I've updated the [release](https://github.com/shycats/VirtuCameraBlender/releases/download/v1.0.0/VirtuCameraBlender-cp37-macos64-v1.0.0.zip) with a new build that should be compatible from MacOS 10.12 (Sierra) and above. Please, let me know if it works for you. Thanks!

**Comment by vanaus** [comment]
> @vanaus I've updated the [release](https://github.com/shycats/VirtuCameraBlender/releases/download/v1.0.0/VirtuCameraBlender-cp37-macos64-v1.0.0.zip) with a new build that should be compatible from MacOS 10.12 (Sierra) and above. Please, let me know if it works for you. Thanks

works beautifully!!! Preciate y’all!!

**Comment by shycats** [comment]
Great! :) Closing the issue.
