### ISSUE TITLE
Error in macOS Blender 2.93a

### ISSUE THREAD

**Issue by pentagramwookie** [shycats/VirtuCameraBlender#4]
<img width="2560" alt="Screen Shot 2021-03-18 at 11 11 33 PM" src="https://user-images.githubusercontent.com/15253782/111739000-86c05180-883f-11eb-8481-6fcc49de6fb9.png">

Works great in 2.92!! super fun! what a great addon+app combo, love this!

Just heads up, you may already know but it's not working in 2.93a

thanks!!!

best regards

**Comment by shycats** [comment]
Hello,

Thanks for reporting this, Blender 2.93 (Alpha) is switching to Python version 3.9.1 and that is causing the error.

I'm working on a build that will work in that Python version and will release it soon.

**Comment by shycats** [comment]
Added support for Blender 2.93 and 3.0
Closing the ticket.
