### ISSUE TITLE
Possible to use the virtual camera from the computer ?

### ISSUE THREAD

**Issue by tsaquet** [shycats/VirtuCameraBlender#5]
Hello !

This add-on is very promising ! I would like to know if it is possible to get the stream directly from the computer where Blender is executed ? It would be awesome - and very useful for me - to be able to read the stream from a browser, or from vlc for instance :)

If not, do you think it would be something easy to develop from what you did ?

Thank you !

**Comment by shycats** [comment]
Hello!

At the moment is not possible to stream the video feed to another player, I think it's probably not easy to develop.
Maybe you can try with VNC-like software to see your computer screen from other computers.

Cheers!
