### ISSUE TITLE
Blender 2.93 doesn't supports?

### ISSUE THREAD

**Issue by gqbay** [shycats/VirtuCameraBlender#7]
Hello! Thanks for your great application! 
I have an issue. Plugin works on 2.83 but not in 2.93
Would you kindly fix it please

**Comment by shycats** [comment]
Hello @gqbay, Blender 2.93 is still in Alpha and is not supported at the moment, but I'm working on a build that will work on that version and will release it soon, I will let you know when it's ready.

**Comment by gqbay** [comment]
Thank a lot! Will be waiting =)

**Comment by shycats** [comment]
[Released a version](https://github.com/shycats/VirtuCameraBlender/releases/tag/v1.0.2B) for Blender 2.93 and 3.0
enjoy :)
