### ISSUE TITLE
Problem connecting iPhone to Mac, Blender 2.93 - 3.0

### ISSUE THREAD

**Issue by enzyme69** [shycats/VirtuCameraBlender#8]
I just tested latest addon for Blender 2.93 and 3.0, both unable to connect to iPhone, eventhough they are using the same WIFI. Not sure why. 

Something wrong with QR and the address, I thought, but I checked and manual input, none seems to be working.

**Comment by enzyme69** [comment]
I tried with older version 2.92 and older addon still works and connect without issue. However the camera preview via the app is blank.

**Comment by shycats** [comment]
Hello, I’m sorry you are having problems to connect.

What is the plug-in version for 2.92 where the connection is working but not the preview? You can find the version number above the “start serving” button.

Also, please check if it works by temporarily disabling the firewall in System Preferences > Security & Privacy > Firewall

Thank you.

**Comment by enzyme69** [comment]
UPDATE:
With 2.92 I use version 1.0.2. I tested again just now and now the preview camera on the app working again. This version never have connection issue unlike 2.93 and 3.0.

I re-install for 3.0 once again, but still no luck. Still "Connecting" and then Error popup. I checked both device, same wifi, same address. Manual does not work.

I tried disabling firewall and still the same issue.

**Comment by shycats** [comment]
Thank you so much for the info.

Is it possible that you have multiple Blender sessions open at the same time, with the add-on running?
Also, is this happening with just the cube default scene when you open Blender? Just to discard something related to a scene setting.

Are you familiar with the MacOS Terminal? if you open Blender from there, errors might be printed when you start serving o try to connect, and that could give us more information about the problem. If you feel comfortable with this, just open the Terminal App  from `/Applications/Utilities/Terminal.app` and open Blender from there by using the following command:
```
/Applications/Blender.app/Contents/MacOS/Blender
```
You may need to replace `Blender.app` with your Blender 2.93 app name if it has been renamed, or the path to the app if it's installed in another location.

**Comment by enzyme69** [comment]
I only run 1 Blender instance for this. I also have tried removing the previous version of the addon and checking if I double install it. Nothing works.

This is happening with just the default cube opening scene. I cannot link via QR or manual.

As for error in terminal, as soon I create QR code link it seems to stop:

```
VirtuCamera: Listening on TCP port 23354
VirtuCamera: Stopped serving
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Applications/BLENDER_293_beta/Blender.app/Contents/Resources/2.93/python/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Applications/BLENDER_293_beta/Blender.app/Contents/Resources/2.93/python/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "vc_core.pyx", line 1306, in virtucamera.vc_core.VCServer._stop_serving_thread
  File "vc_core.pyx", line 1310, in virtucamera.vc_core.VCServer._stop_serving_thread
  File "vc_core.pyx", line 1348, in virtucamera.vc_core.VCServer._stop_tcp_accept
socket.timeout: timed out
Saved session recovery to '/var/folders/r3/13y_zxhn0557ftnbz9xrt7x00000gn/T/quit.blend'
Exception in module unregister(): '/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/oscurart_bake_pbr.py'
Traceback (most recent call last):
  File "/Applications/BLENDER_293_beta/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 438, in disable
    mod.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/oscurart_bake_pbr.py", line 517, in unregister
    bpy.utils.unregister_class(OBJECT_OT_add_object)
NameError: name 'OBJECT_OT_add_object' is not defined
Exception in module unregister(): '/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/spring_bones.py'
Traceback (most recent call last):
  File "/Applications/BLENDER_293_beta/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 438, in disable
    mod.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/spring_bones.py", line 867, in unregister
    del bpy.types.Object.sb_collide
AttributeError: sb_collide
cleaning Sverchok cache
Error unregistering module: sverchok.nodes.scene.get_objects_data
unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
sv: remove app.handlers
{}
2021-05-24 20:04:08,959 [INFO] root: INFO: Unregistered Photogrammetry Import Export Addon
Exception in module unregister(): '/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/sverchok-open3d-master/__init__.py'
Traceback (most recent call last):
  File "/Applications/BLENDER_293_beta/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 438, in disable
    mod.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/sverchok-open3d-master/__init__.py", line 192, in unregister
    settings.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/sverchok-open3d-master/settings.py", line 79, in unregister
    bpy.types.SV_PT_SverchokUtilsPanel.remove(sv_draw_update_menu_in_panel)
AttributeError: 'module' object has no attribute 'SV_PT_SverchokUtilsPanel'
Exception in module unregister(): '/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/__init__.py'
Traceback (most recent call last):
  File "/Applications/BLENDER_293_beta/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 438, in disable
    mod.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/__init__.py", line 176, in unregister
    auto_load.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/auto_load.py", line 38, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMetaPropGroup' instance (may not be registered)
```

**Comment by shycats** [comment]
Thank you for the terminal output, it's really helpful. 

It looks like some other add-on or Blender itself is changing the default behavior of Python's network connections, as `socket.timeout: timed out` never should happen.

I'm working on a fix that takes into account this altered behavior, I will let you know as soon as I have it so you can test if it solves the problem.

**Comment by shycats** [comment]
Hello @enzyme69,

I've published a new version:
[https://github.com/shycats/VirtuCameraBlender/releases/tag/v1.0.3B](https://github.com/shycats/VirtuCameraBlender/releases/tag/v1.0.3B)

You will need to restart Blender after installing it, to make Blender properly unload the previous version.

please, let me know if it works for you on Blender 2.93 or 3.0.

Cheers!

**Comment by enzyme69** [comment]
With this version, I can link via QR, and connection is made in Blender 3.0.

I also try on app linking the camera, and it is moving in realtime, can record keyframe etc. However when I tap the Eye icon, the app seems to reset and connection is lost again.

**Comment by shycats** [comment]
Great! at least it connects :) one step at a time.

Sorry to bother you again, please could you provide the output of the terminal when you tap in the eye? Are there any errors? 

Thanks!

**Comment by enzyme69** [comment]
No error message on terminal, it simply goes back to front menu on the app. Showing a quick still image of the camera view but only for a split second.

**Comment by shycats** [comment]
Your Python environment in Blender is somehow in a modified state, different from default (Maybe an add-on with bad programming practices is causing this) so I'm not able to reproduce the problem and I have to guess the source of the problem.

I've made some new changes, I think it should finally work now (fingers crossed).

I updated the release in
https://github.com/shycats/VirtuCameraBlender/releases/tag/v1.0.3-2.93
You can download it again and make sure you remove the previous one before installing it, as it has the same version number.

Please, let me know if it works now.

Cheers!

**Comment by enzyme69** [comment]
I tested with the latest version and seems this one works the best although with my machine, it seems to stutter slightly. 

You might be right with the python is in modified state, I played with sudo etc before and might have something to do with this. But anyhow, this latest version seems works ok:
- QR code link works
- Linking live 3D View Camera works
- Slightly stutter with the iPhone view

I will try with a different account, clean Python and Blender 2.93 also.

Thanks for the fix on this issue. Great app and addon!

**Comment by enzyme69** [comment]
Actually the stutter is really unbearable with and without live view into iPhone :( I test it and it looks like this:

https://user-images.githubusercontent.com/3952687/120087811-90fba780-c12e-11eb-9a83-4216706ff923.mov

It's not useable at this point. 

It was smooth before.

**Comment by enzyme69** [comment]
UPDATE:
After restarting my machine (MacBookPro 2017), the performance seems better and less stutter. Maybe my wifi has something to do with it.

I guess we can close this issue. Thanks have a great Sunday.
